### ISSUE TITLE
Question: does it sync states of tasks?

### ISSUE THREAD

**Issue by katspaugh** [somebox/jira-tracker-for-trello#4]
Like to whom a task is assigned, if it's done or not.

Thanks!

**Comment by somebox** [comment]
It does not sync assignments at the moment. It would be possible to extend it. To do this, you would probably need a mapping of JIRA to Trello users. I thought about this but decided not to go in this direction, because mapping users is manual labor. If you could think of a way, a pull would be appreciated!

**Comment by katspaugh** [comment]
Thanks for you answer! Got it.

As yet, It's not an urging necessity for us, so I'm just researching possibilities. Closing this issue for now.
